### ISSUE TITLE
Documentation menu scrollbar is too big in height

### ISSUE THREAD

**Issue by martijn00** [MvvmCross/mvvmcross-docs#32]
I can't see the last couple of items.

**Comment by martijn00** [comment]
@MarcBruins this is not fixed properly. I can see the last item, but the scrollbar scrolls under the bottom of the page, which means the height is incorrect.

The same problem is also for the main content, where if there is a scroll, the last couple of things are not visible.

**Comment by MarcBruins** [comment]
The header has a position relative by default from the theme. That's why the overflow of the documentation menu content is clipped off and the height is incorrect. I've noticed the same problem for the main content and would suggest the same solution as the documentation menu, that means however that the scrollbar will be larger then the page.

Not sure in what other way we could correct this issue. Maybe someone else knows?
